(define (parrot-speed parrot-type num-coconuts voltage nailed)
    (define (base-speed) 12.0)
    (define (load-factor) 9.0)
    (define (compute-base-speed-for-voltage voltage)
        (min 24.0 (* voltage (base-speed))))
    (cond
        ((eq? parrot-type 'european-parrot)
            (base-speed))
        ((eq? parrot-type 'african-parrot)
            (max 0.0 (- (base-speed) (* (load-factor) num-coconuts))))
        ((eq? parrot-type 'norwegian-blue-parrot)
            (if nailed 0.0 (compute-base-speed-for-voltage voltage)))
        (else (raise 'Should-be-unreachable))
    )
)
